unique_ids:
  assets:
    standard-page.html: YEIKTROIHNKNRJB43FVNYHNU5MSHKJIE
    theme.css: HCYRM35YQKABDFL2N3XK5KLZLXUKPFT4
  forms:
    Form1: 7JTJGOPV7V5RSVXYD2WFVCKXAPOTLLDS
  modules: {}
  scripts: {}
  server_modules: {}
